using System.Collections;
using UnityEngine;

public class PlayerAttack : MonoBehaviour
{
    public GameObject attackRange;
    private AttackRange atk;
    public float attackDuration = 0.2f;
    private bool coolDown;
    public float timeCoolDown = 1f;


    public AudioSource VFXSoundClick;
    public AudioClip musicClipSoundClick; 

    private bool isAttackingNow; // ðŸ”¹ biáº¿n theo dÃµi tráº¡ng thÃ¡i Ä‘ang táº¥n cÃ´ng

    void Awake()
    {
        atk = attackRange.GetComponent<AttackRange>();
        coolDown = false;
        isAttackingNow = false;
        VFXSoundClick.clip = musicClipSoundClick;
    }

    void Update()
    {
        if (Input.GetMouseButtonDown(0) && !coolDown)
        {
            StartCoroutine(DoAttack(atk));

        }
    }

    public bool isAttacking()
    {
        return isAttackingNow;
    }

    IEnumerator DoAttack(AttackRange atk)
    {
        coolDown = true;
        isAttackingNow = true;   // ðŸ”¹ báº­t tráº¡ng thÃ¡i Ä‘ang táº¥n cÃ´ng
        atk.ResetHitList();
        atk.canAttack = true;

        yield return new WaitForSeconds(attackDuration);

        VFXSoundClick.Play();

        atk.canAttack = false;
        isAttackingNow = false;  // ðŸ”¹ táº¯t tráº¡ng thÃ¡i táº¥n cÃ´ng

        yield return new WaitForSeconds(timeCoolDown);
        coolDown = false;
    }
}
